[package]
name = "gmrs"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = { version = "1.0", features = ["derive"] }
rayon = "1.7.0"
rand = "0.8.5"
rand_distr = "0.4.3"
ndarray = "0.15.0"

[dev-dependencies]
clap = { version = "4.4.5", features = ["derive"] }
serde_yaml = "0.9"
